### ISSUE TITLE
dataset used to pretrain model

### ISSUE THREAD

**Issue by Cjiangbpcs** [haofanwang/mxnet-headpose#1]
Nice work! And I have a few questions and wonder whether you could provide some insights:

1. dataset used to pretrain your model, did you use one of the data sets listed in the original Pytorch github? 300W_LP or AFLW2000?

2. pretrained resnet50 model, looks like you did not use the pretrained resnet50 weights as in the original Pytorch version, why?

3. time to train your model, how long did it take to train your model on, say 300W_LP datasets?

Thanks.

**Comment by haofanwang** [comment]
Hi, @Cjiangbpcs 

1. We do not use any public dataset to train our model,  we use our own infra-red datasets in order to fit specific scene. 
2. Yes, we do not implement a Resnet50 model, we only test a Resnet18 and a shallow CNN here. For the same reason, we already have enough training data, so we don't use any pretrained weight. Recent research done by Kaiming He also has proved that pretrained model is not necessary.
3. We don't train on 300W_LP dataset. The speed to train a model depends on your setting and device, such as input size, input channel and the complexity of your network. On a single TITAN X, it takes about 5 minutes to train 15 epochs on a 300K dataset with 48x48x1 input.

You could generate your our lst and rec on public datasets if you are intereted in.

**Comment by Cjiangbpcs** [comment]
@haofanwang Thank you, these are very helpful. About your own datasets, how did you annotate the images' angels? Thanks.

**Comment by haofanwang** [comment]
Here are two ways we have tried to annotate head pose:

    1. Annotate facial landmarks, in our case, we use 68 points. Then, use SolvePnP tool to calculate 3D head pose. (Some public datasets also use this way)
    2. Use attitude gyro to get very accurate head pose. (But this is very time-costing and expensive)

In fact, the head pose calculated by SolvePnP is not very accurate for large pose, so we may try the second way later. But, It's not recommended to build up your own dataset if you don't have enough resource, public datasets like 300W_LP is already enough to verify your idea.

**Comment by Cjiangbpcs** [comment]
Thanks for the detailed reply!

I wonder whether you could answer a couple of further questions about your pretrained model:

1. Have you also trained your model using 300W_LP? If so, how many epochs did it take to converge? If no, for your own datasets, how many epochs did it take to converge? Will the 12000 images of 300W_LP be too few so your model will overfit?

2. Looks like your pretrained model used classical model architecture, have you also tried resnet34 or resnet50 architecture? 

3. Do you have a script to inference a video instead of an image? 

Thanks in advance.

**Comment by haofanwang** [comment]
@Cjiangbpcs Sorry for delay, I'm really busy these days(in applying graduate school, writing thesis and some personal issues).

1. As a matter of experience, it takes about 5 - 15 epochs to converge depending on the your network and scale of dataset. 300W_LP contains more than 120K images (including flip images), and it's not a small dataset for head pose estimation, please make sure you download the whole dataset.
2. Yes, better model architechture can lead to better performance. The classical architecture is just a typo and we do not focus on the network itself.
3. Yes, but I cannot release it now. It's should be simple to write a script for video inference on yourself, feel free to PR.

**Comment by Cjiangbpcs** [comment]
Thanks and close this issue.
